apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x4ak2st7e-java-springboot
  janus-idp.io/tekton: x4ak2st7e-java-springboot
  backstage.io/kubernetes-id: x4ak2st7e-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x4ak2st7e-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
